---
database_file: "/Users/lhalstro/.timetrap/.timetrap.db"
round_in_seconds: 900
append_notes_delimiter: ", "
formatter_search_paths:
- "/Users/lhalstro/.timetrap/formatters"
default_formatter: text
auto_sheet: dotfiles
auto_sheet_search_paths:
- "/Users/lhalstro/.timetrap/auto_sheets"
default_command:
auto_checkout: false
require_note: false
note_editor: false
# note_editor: "vim"
week_start: Monday
